### PR TITLE
added some commands to add the ssh key to the ssh-agent to retain the…

### PR DESCRIPTION
**Pull request by elstamey**
… key authorization

### CODE REVIEW

**Comment by elstamey** [comment]
screen shot 2015-06-10 at 2 49 26 pm

**Comment by elstamey** [comment]
I don't see the specific error in the log above, so where can I read the output of the modified command?

**Comment by mdwheele** [comment]
So maybe how the `shell` provisioners work is it's a different shell session per provisioner. That makes sense, I think? I honestly don't know. 

If that is the case, then it's equivalent to opening up a terminal window, starting ssh-agent, closing it out (terminating the agent), then coming back in a new window and trying to `ssh-add` to an agent that isn't running.

**Comment by mdwheele** [comment]
I can take it from here and  hammer it out so you can keep working. It'd probably be cleaner to organize this all in one bash script and pass arguments to it rather than multiple shell provisioners.

**Comment by elstamey** [comment]
ruby > bash

**Comment by mdwheele** [comment]
Working on this now.

**Pull request closed without merging**
