### PR TITLE
Add .dev extension to hostname

### PR DESCRIPTION
**Pull request by jlmaners**
By adding `.dev` as an extension onto the vagrant hostname, currently **kraken** it affords several conveniences for doing local development, without impacting current workflows.

If a user of the VM chooses to install the [Vagrant::Ghost Plugin](https://github.com/10up/vagrant-ghost) an entry will be added to the local `/etc/hosts` file on vagrant up and removed on vagrant halt.

This allows for a couple of things:
1. Developers can rely on **kraken.dev** being a domain name in their environment
2. It allows for ease in utilizing a multisite development install of WordPress
3. No other changes to existing workflows are required

@mdwheele I'd appreciate any insight if adding `.dev` causes other issues in use cases in which I'm unaware.

### CODE REVIEW

**Comment by jlmaners** [comment]
This would resolve #52

**Comment by mdwheele** [comment]
Anything preventing you from just accessing the hostname without extension? Does ghost let us programmatically specify additional hosts? The docs suggest so but change log is ambiguous as to whether it uses this "aliases" file or let's you do your own thing. 

Plugin looks to be in high flux too. Is there anything more stable you've found for managing hosts? Is rather do this right once and for all rather than revisiting such a fundamental change. Switching plugins midstream will be annoying depending on how they manage hosts (most are using some sort of fenced config). 

I'll go ahead and make this change; but to "local.dev".

**Comment by jlmaners** [comment]
I went with this particular plugin because the original one I used, which accomplished the same thing, hasn't been touched/updated in almost 2 years. This particular one is backed by 10Up so I figured it'd have some support behind it. 

The `.dev` extensions is needed for the NCSU CDN assets to load. It didn't like just **kraken**. I believe the allowed hosts are:
- `*.dev`
- `localhost`
- `*.ncsu.edu`

There are others hosts management plugins, but all have seemed highly opinionated. This one seemed to have the least barrier to entry, with no additional markup required in the vagrant file (or the kraken.rb script).

**Comment by mdwheele** [comment]
I'll look at it. That's the thing. I need to be able to control it from vagrant side to marry with our config. Don't want N points of entry on config

**Comment by jlmaners** [comment]
Per our discussion at Global Village this morning, I changed the hostname to `local.dev`

**Pull request closed without merging**
