### PR TITLE
attempt to fix issue #61

### PR DESCRIPTION
**Pull request by elstamey**
I believe this fixes issue #61

### CODE REVIEW

**Comment by elstamey** [comment]
I'm testing this now

**Comment by elstamey** [comment]
This seems to be fixed.  will you test @mdwheele or @mcamiano ?

**Comment by elstamey** [comment]
i accidentally referenced the wrong issue number in the commit, and fixed that, which is why the commit moved to the bottom

**Comment by mdwheele** [comment]
Awesome. Thanks @elstamey!

**Pull request merged**
